services:
  - type: web
    name: django-invoice
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn invoicing.wsgi
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - fromGroup: render_postgres
        key: DATABASE_URL

databases:
  - name: postgres
    plan: free
    ipAllowList: []
    envVarKey: render_postgres
